[tool.poetry]
name = "poetry-esercizio"
version = "0.1.0"
description = ""
authors = ["skybelenm <maria.belen.nttdata@skytv.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
